#Done --> ./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/2nd-test-r-ashwins-68.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#Done --> ./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/3rd-test-alastair-cooks-190.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#To Check Viz -->./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/day-2-karnataka-lead-by-282-runs.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#To Check Viz --> ./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/day-3-clinical-india-in-sight-of-win.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#Done--> ./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/england-have-a-warning-for-kohli.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#Done --> ./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/IPL2017 M51.avi" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#Done --> ./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/IPL2017 M7.avi" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/Game 15 highlights - Patriots vs Tridents _ CPL15.avi" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/Game 21 highlights - Tallawahs vs Tridents _ CPL15.avi" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/Game 3 Highlights - Tridents vs Tallawahs _ CPL15.avi" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/india-seal-40-win-over-england.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/jadejas-flashy-51-propels-india.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/James Faulkner.avi" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/nz-tie-odi-series-in-thriller.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/ouch-bhuvi-hits-pandya-on-the-head.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/Pat Cummins.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/Test Highlights Ind Vs Aus.avi" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/tn-avoid-loss-andhra-take-3-points.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/(Top-10 ) Most Weird Cricket Shots HD Cricket Video Compilation.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_0qWsWsy19B8.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_1ak5NVTG99M.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_2wj3XisGb5s.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_3A3lyh0DFB8.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_49z08c52xek.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_4wZC7hCnx2c.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_5RZsOmxFLnE.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_6zCZrinZqfs.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_9Lzh1kY-L3U.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_9Y98Fp6L0I8.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_a4kVm6fcjVc.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_aCcL5gWTF-M.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_BiPSFdQ_1gg.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_CbA7QYFoClg.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_cIdg1_NZZFo.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_cjJq_kylTgk.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_Did4_6qggM4.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_E9Mh9N0fVus.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_ext5lB1P0M4.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_F4A5Rwz1qro.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_fWgZmektoKM.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_FyoCH7C1dgg.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_Ge1NwaYqSck.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_Iu0AfTbPvQk.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_jkseCZwu4pU.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_joGTw1k4nHk.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_k_xCTt0MTMw.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_lOcdmZSBNhY.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_nAJtJCV1OGA.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v___npn7yG5uY.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_nTlPm8DwH6U.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_ofn6GVIxVww.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_Oheq3_eE0JQ.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_oKRnIiCQqns.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_orkdcO4Qiqg.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_p7VNeiUp_KU.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_PQ9oGh9vBFo.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_qgP_PqY6m1k.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_qTAFseWcQjc.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_qYFayMVNKqQ.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_rfSwVDWl9Xk.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_s1oUARdPsqc.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_s9ka8CsbhLs.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_sHU73rPNoI8.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v__TVLJa0vSGE.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_UMdFYreE8Nc.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v__USsQHUxyIA.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_USX1A_f212I.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_USxaFJBW5BU.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_Utm9mTxBWLI.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_V3rVDrtJ0LQ.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_V8-DwDU-dxc.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_vVrhXY8w42o.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_wbfv1qOG3WM.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_Za_bHmo5JiE.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_zERGdoYe1Ro.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_zoIhS3-eJhk.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/v_zsQFNWA_ehk.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
#./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_train_set/WCT20 Women India Vs Bangladesh.mp4" --write_json /home/arpan/cricket/output_json_main_train --display 0 --render_pose 0
