./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/2nd-test-kohli-pujara-give-india-control.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/Airtel 2nd ODI Pakistan Vs India Highlights.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/allround-mumbai-claim-first-win.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/Best Fielding in Cricket History - Top Cricket Fieldings - Cricket Highlights 2016.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/day-1-karnataka-dominate-with-3273.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/dhonis-maiden-t20i-fifty.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/dhoni-smashes-23-off-last-over.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/Game 1 Highlights - Tridents vs Amazon Warriors _ CPL15.avi" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/Game 30 highlights - Amazon Warriors vs Red Steel _ CPL15.avi" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/ICC World T20 2014 Pakistan Vs Australia Highlights.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/IND 105_10 IN RETURN BAN 58_10 [HD].mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/IPL2017 M50.avi" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/IPL2017 M52.avi" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/PayTM Test Highlights.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_aivHI4Vdzpk.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_dpgSpLLrDTY.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_FyM4DXOS_VM.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/vidarbha-complete-easy-win-on-day-4.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_ietiN62_bj8.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_JK3V4hRpg_s.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_Js3XBQpJjRQ.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_KisG8mgjGIU.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_KyHQcii7I88.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_lnCugIDpkZk.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_MsMqi61_mBs.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_oHD1CZYQVoU.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_oJDUURdwmqg.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_Om5Tp3JaJ3c.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_SoR34XoFQaQ.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_Vng65yQHIvw.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/v_zbma_pYGO2A.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_val_set/World Record Score Chase 438 in Cricket History Ever - Cricket Highlights.mp4" --write_json /home/arpan/cricket/output_pose_main_val --display 0 --render_pose 0