./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/1st-odi-kohlijadhavs-200run-stand.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/5th-test-rahuls-199-vs-eng.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/day-1-england-ride-on-root-moeen.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/dhonis-134-tames-england.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/Game 28 highlights - Amazon Warriors vs Tridents _ CPL15.avi" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/Game 7 highlights - Tridents vs Patriots _ CPL15.avi" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/Highlights Australia v India, MCG.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/india-win-thriller-in-nagpur.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/IPL2017 M11.avi" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/IPL2017 M42.avi" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/IPL Super over.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/karnataka-stamp-class-on-day-1.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/same-yuvraj-different-comeback.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/Top 20 Crazy Moments In Cricket.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_19sVHiSbanM.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_5wgFl-4X2-Q.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_6mi0vnPncSc.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_BBshznJqWFE.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_EWnlXR7dqvU.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_ExNKybLxmoc.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_LtgHf51-i4U.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_M_92i_kasAs.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_Mv4mzOxKyE8.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_QpwaoVZSChY.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_RSi3SiCJJsA.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_Tb1V2UNSe3g.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v__tEb7K5jc7M.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_-vlWskdBSQw.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/v_-Wp7AhmHNAI.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
./build/examples/openpose/openpose.bin --video "/home/arpan/DATA_Drive/Cricket/dataset_25_fps_test_set/yuvi-msd-give-ind-series-win.mp4" --write_json /home/arpan/cricket/output_pose_main_test --display 0 --render_pose 0
